# Generated by Django 4.2.4 on 2023-09-07 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otpcode',
            name='expire',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('laki-laki', 'Laki-laki'), ('perempuan', 'Perempuan')], max_length=10, null=True),
        ),
    ]
