# Generated by Django 4.2.4 on 2023-08-25 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_alter_user_birth_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nik',
            field=models.CharField(blank=True, max_length=16, null=True, unique=True),
        ),
    ]
