# Generated by Django 4.2.4 on 2023-09-02 01:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('car_type', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('color', models.CharField(max_length=50)),
                ('transmission', models.CharField(choices=[('A', 'Automatic'), ('M', 'Manual')], max_length=10)),
                ('license_plate', models.CharField(max_length=15, unique=True)),
                ('passenger_capacity', models.PositiveIntegerField()),
                ('fuel_capacity', models.DecimalField(decimal_places=2, max_digits=5)),
                ('description', models.TextField()),
                ('picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('is_booked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Rental',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('check_out_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('A', 'Aktif'), ('P', 'Menunggu'), ('C', 'Selesai')], default='Pending', max_length=20)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
