# Generated by Django 4.2.4 on 2023-09-03 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='price',
            field=models.IntegerField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='rental',
            name='status',
            field=models.CharField(choices=[('A', 'Aktif'), ('P', 'Menunggu'), ('C', 'Selesai')], default='P', max_length=20),
        ),
    ]
