# Generated by Django 4.2.4 on 2023-08-24 07:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_rename_name_customer_full_name_customer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rental',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
